### ISSUE TITLE
getting no response from watson because url has not been changed 

### ISSUE THREAD

**Issue by autkid** [Watson-Personal-Assistant/simple_WA_slackbot#1]
i have changed the url from/v2/api/converse/expertiseCollection/collectionname?apikey to /v2/api/skillSets/skillsetname/converse?apikey...... it worked

**Comment by troyibm** [comment]
fixed with commit https://github.com/Watson-Personal-Assistant/simple_WA_slackbot/commit/63c04ebed2d2d55215a734b6eceec1adf2520f57
